# Generated by Django 3.1.4 on 2021-01-18 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must start with '0' or '+44',contain 0-9, spaces or - symbols", regex='^(?:0|\\+?44)(?:\\s|\\-)?(?:\\d(?:\\s|\\-)?){9,10}$')]),
        ),
    ]
