# Generated by Django 3.1.4 on 2021-01-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210111_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'requestee'), (2, 'volunteer'), (3, 'admin')]),
        ),
    ]
