# Generated by Django 3.1.4 on 2021-01-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210111_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'requestee'), (2, 'volunteer'), (3, 'admin')], default=3),
        ),
    ]
