# Generated by Django 3.1.4 on 2021-02-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210130_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['latitude'], name='accounts_us_latitud_d70555_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['longitude'], name='accounts_us_longitu_823ebc_idx'),
        ),
    ]
