# Generated by Django 3.1.4 on 2021-02-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
