# Generated by Django 3.1.4 on 2021-01-12 02:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_auto_20210112_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('GRO', 'Groceries'), ('PHA', 'Pharmacy'), ('DOG', 'Dog Walk'), ('HOS', 'Hospital Appointment'), ('CHAT', 'Phone Chat'), ('ANY', 'Other')], max_length=5)),
                ('min_duration', models.IntegerField()),
                ('DBS_required', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('GRO', 'Groceries'), ('PHA', 'Pharmacy'), ('DOG', 'Dog Walk'), ('HOS', 'Hospital Appointment'), ('CHAT', 'Phone Chat'), ('ANY', 'Other')], max_length=5)),
                ('description', models.TextField(blank=True, default='')),
                ('dbs_needed', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('min_duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('status', models.CharField(choices=[('OP', 'Open'), ('EXP', 'Expired'), ('AS', 'Assigned'), ('CL', 'Canceled'), ('DN', 'Completed')], default='OP', max_length=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.requestee')),
                ('volunteer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.volunteer')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
