# Generated by Django 3.1.4 on 2021-01-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktype',
            name='task_type',
            field=models.CharField(choices=[('GRO', 'Groceries'), ('PHA', 'Pharmacy'), ('DOG', 'Dog Walk'), ('HOS', 'Hospital'), ('CHAT', 'Phone Chat'), ('ANY', 'Other')], max_length=5),
        ),
    ]
