# Generated by Django 3.1.4 on 2021-02-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210131_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['end_time'], name='tasks_task_end_tim_4bc5e1_idx'),
        ),
    ]
