# Generated by Django 3.1.4 on 2021-01-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210101_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('EXP', 'Expired'), ('AS', 'Assigned'), ('CL', 'Canceled'), ('DN', 'Completed')], default='OP', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('GRO', 'Groceries'), ('PHA', 'Pharmacy'), ('DOG', 'Dog Walk'), ('HOS', 'Hospital Appointment'), ('CHAT', 'Phone Chat'), ('ANY', 'Other')], max_length=5),
        ),
    ]
