//import axios from "axios"
export default function initialTasks() {
    /* eslint-disable no-extend-native */
    /*const initialTasks1 =  axios.post("http://localhost:8000/api/tasks/").catch(function (error) {
          console.log(error.request); console.log(error.config)})
          */

    Date.prototype.addHours = function (h) {
        this.setHours(this.getHours() + h);
        return this;
    };

    const initialTasks = [
        {
            id: 1,
            lastName: "Snow",
            firstName: "Jon",
            taskType: "Shopping",
            taskDetails: "I need help with Shopping from Tesco",
            start: new Date().addHours(2),
            end: new Date().addHours(4),
            distance: 1,
            volId: 1,
            status: "Assigned",
        },
        {
            id: 2,
            lastName: "Lannister",
            firstName: "Cersei",
            taskType: "Dog Walking",
            taskDetails: "I need help with dog walkingevery morning and afternoon",
            start: new Date().addHours(2),
            end: new Date().addHours(4),
            distance: 1,
            volId: 1,
            status: "Assigned",
        },
        {
            id: 3,
            lastName: "Lannister",
            firstName: "Jaime",
            taskType: "Shopping",
            taskDetails: "I need help with Shopping from Asda",
            start: new Date().addHours(5),
            end: new Date().addHours(10),
            distance: 2.3,
            volId: 1,
            status: "Completed",
        },
        {
            id: 4,
            lastName: "Stark",
            firstName: "Arya",
            taskType: "Pharmacy",
            taskDetails: "I need help with picking up my prescription from local gp",
            start: new Date().addHours(20),
            end: new Date().addHours(24),
            distance: 0.8,
            volId: null,
            status: "Open",
        },
        {
            id: 5,
            lastName: "Targaryen",
            firstName: "Daenerys",
            taskType: "Hospital",
            taskDetails: "I need help to drop off and pick up from my hospital",
            start: new Date().addHours(20),
            end: new Date().addHours(24),
            distance: 2,
            volId: null,
            status: "Open",
        },
        {
            id: 6,
            lastName: "Melisandre",
            firstName: null,
            taskType: "Phone Call",
            taskDetails: "I need someone to give me a call to have a chat",
            start: new Date().addHours(20),
            end: new Date().addHours(24),
            distance: 5,
            volId: null,
            status: "Open",
        },
        {
            id: 7,
            lastName: "Clifford",
            firstName: "Ferrara",
            taskType: "Shopping",
            taskDetails: "I need help with Shopping from Tesco",
            start: new Date().addHours(-20),
            end: new Date().addHours(-16),
            distance: 4,
            volId: null,
            status: "Open",
        },
        {
            id: 8,
            lastName: "Frances",
            firstName: "Rossini",
            taskType: "Other",
            taskDetails: "I need help with mowing my garden",
            start: new Date().addHours(-20),
            end: new Date().addHours(-16),
            distance: 2,
            volId: null,
            status: "Open",
        },
        {
            id: 9,
            lastName: "Roxie",
            firstName: "Harvey",
            taskType: "Shopping",
            taskDetails: "I need help with Shopping from Sainsbuyrys",
            start: new Date().addHours(-20),
            end: new Date().addHours(-16),
            distance: 3,
            volId: null,
            status: "Open",
        },
        {
            id: 10,
            lastName: "Indra",
            firstName: "Thapa",
            taskType: "Medical",
            taskDetails: "I need help with picking up my prescription",
            start: new Date().addHours(-20),
            end: new Date().addHours(-16),
            distance: 3,
            volId: null,
            status: "Open",
        },
        {
            id: 11,
            lastName: "Paanas",
            firstName: "Thapa",
            taskType: "Medical",
            taskDetails: "I need help with picking up my prescription",
            start: new Date().addHours(-20),
            end: new Date().addHours(-16),
            distance: 3,
            volId: null,
            status: "Open",
        },
        {
            id: 12,
            lastName: "Paanas",
            firstName: "Thapa",
            taskType: "Medical",
            taskDetails: "I need help with picking up my prescription",
            start: new Date().addHours(-100),
            end: new Date().addHours(-80),
            distance: 3,
            volId: null,
            status: "Open",
        },
        {
            id: 13,
            lastName: "Kate",
            firstName: "Middleton",
            taskType: "Medical",
            taskDetails: "I need help with picking up my prescription",
            start: new Date().addHours(20),
            end: new Date().addHours(40),
            distance: 3,
            volId: null,
            status: "Open",
        },
        {
            id: 14,
            lastName: "Joe",
            firstName: "Kelly",
            taskType: "Shopping",
            taskDetails: "I need help with Shopping from Tesco",
            start: new Date().addHours(90),
            end: new Date().addHours(140),
            distance: 4,
            volId: null,
            status: "Open",
        },
        {
            id: 15,
            lastName: "Frances",
            firstName: "Rai",
            taskType: "Other",
            taskDetails: "I need help with mowing my garden",
            start: new Date().addHours(20),
            end: new Date().addHours(40),
            distance: 2,
            volId: null,
            status: "Open",
        },
        {
            id: 16,
            lastName: "Roxie",
            firstName: "Raymond",
            taskType: "Shopping",
            taskDetails: "I need help with Shopping from Sainsbuyrys",
            start: new Date().addHours(20),
            end: new Date().addHours(40),
            distance: 3,
            volId: null,
            status: "Open",
        },
    ];
    return initialTasks;
}
