export default function initialTasks() {
    const initialTasks = [
        {
            id: 1,
            lastName: "Snow",
            firstName: "Jon",
            taskType: "Shopping",
            taskSummary: "I need help with Shopping from Tesco",
            date: "2020-12-28",
            distance: 1,
            volId: 1,
        },
        {
            id: 2,
            lastName: "Lannister",
            firstName: "Cersei",
            taskType: "Dog Walking",
            taskSummary: "I need help with dog walkingevery morning and afternoon",
            date: "2021-01-20",
            distance: 1,
            volId: 1,
        },
        {
            id: 3,
            lastName: "Lannister",
            firstName: "Jaime",
            taskType: "Shopping",
            taskSummary: "I need help with Shopping from Asda",
            date: "2021-01-28",
            distance: 2.3,
            volId: null,
        },
        {
            id: 4,
            lastName: "Stark",
            firstName: "Arya",
            taskType: "Pharmacy",
            taskSummary: "I need help with picking up my prescription from local gp",
            date: "2021-03-20",
            distance: 0.8,
            volId: null,
        },
        {
            id: 5,
            lastName: "Targaryen",
            firstName: "Daenerys",
            taskType: "Hospital",
            taskSummary: "I need help to drop off and pick up from my hospital",
            date: "2021-01-10",
            distance: 2,
            volId: null,
        },
        {
            id: 6,
            lastName: "Melisandre",
            firstName: null,
            taskType: "Phone Call",
            taskSummary: "I need someone to give me a call to have a chat",
            date: "2021-01-20",
            distance: 5,
            volId: null,
        },
        {
            id: 7,
            lastName: "Clifford",
            firstName: "Ferrara",
            taskType: "Shopping",
            taskSummary: "I need help with Shopping from Tesco",
            date: "2021-01-20",
            distance: 4,
            volId: null,
        },
        {
            id: 8,
            lastName: "Frances",
            firstName: "Rossini",
            taskType: "Other",
            taskSummary: "I need help with mowing my garden",
            date: "2021-01-20",
            distance: 2,
            volId: null,
        },
        {
            id: 9,
            lastName: "Roxie",
            firstName: "Harvey",
            taskType: "Shopping",
            taskSummary: "I need help with Shopping from Sainsbuyrys",
            date: "2021-01-20",
            distance: 3,
            volId: null,
        },
        {
            id: 10,
            lastName: "Indra",
            firstName: "Thapa",
            taskType: "Medical",
            taskSummary: "I need help with picking up my prescription",
            date: "2021-01-20",
            distance: 3,
            volId: null,
        },
        {
            id: 11,
            lastName: "Paanas",
            firstName: "Thapa",
            taskType: "Medical",
            taskSummary: "I need help with picking up my prescription",
            date: "2021-01-20",
            distance: 3,
            volId: null,
        },
        {
            id: 12,
            lastName: "Paanas",
            firstName: "Thapa",
            taskType: "Medical",
            taskSummary: "I need help with picking up my prescription",
            date: "2021-01-20",
            distance: 3,
            volId: null,
        },
        {
            id: 13,
            lastName: "Kate",
            firstName: "Middleton",
            taskType: "Medical",
            taskSummary: "I need help with picking up my prescription",
            date: "2021-01-20",
            distance: 3,
            volId: null,
        },
        {
            id: 14,
            lastName: "Joe",
            firstName: "Kelly",
            taskType: "Shopping",
            taskSummary: "I need help with Shopping from Tesco",
            date: "2021-01-20",
            distance: 4,
            volId: null,
        },
        {
            id: 15,
            lastName: "Frances",
            firstName: "Rai",
            taskType: "Other",
            taskSummary: "I need help with mowing my garden",
            date: "2021-01-20",
            distance: 2,
            volId: null,
        },
        {
            id: 16,
            lastName: "Roxie",
            firstName: "Raymond",
            taskType: "Shopping",
            taskSummary: "I need help with Shopping from Sainsbuyrys",
            date: "2021-01-20",
            distance: 3,
            volId: null,
        },
    ];
    return initialTasks;
}
